language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
  - CODECOV_TOKEN="da25ddcc-410d-4067-bee9-76773796e8bf"

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3

before-install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - composer check
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: dev@livecommerce.com.br